package:
  name: pynpf
  version: devel 

source:
  path: ..

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:

about:
  home: https://github.com/markusstocker/pynpf
  license: "GPL 3.0"
  license_file: "LICENSE.txt"
